apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: auth.artofsurfing.org
  dnsNames:
    - auth.artofsurfing.org

